### ISSUE TITLE
Add scroll View in center aligned popup

### ISSUE THREAD

**Issue by sreekanthkb** [carsonperrotti/CNPPopupController#54] opened 2016-07-13 05:51 UTC
If we add a label and its height greater than screen height then how will we manage it . here is no option to add scroll view to this popup.

**Comment by carsonperrotti** [comment] 2016-07-13 14:19
The library supports adding custom views. You will need to initialize a `UIScrollView`, add your `UILabel` to it, set it's `contentSize`, then inset that scrollview as a custom view as per the documentation. Shouldn't be a problem at all.

**Comment by sreekanthkb** [comment] 2016-07-14 05:34
@carsonperrotti  :Sorry, it is not working. Can you please give an example..??

**Comment by carsonperrotti** [comment] 2016-07-14 15:48
I am sorry, I do not have time to give you a full example, but I will write some quick pseudo code that should help you out. Then I will close this issue as it's question with specific code and not a bug or problem with the library.

let label = UILabel()
label.text = "long string"
label.frame = CGRectMake(0, 0, 280, 900) // Height larger than screen size

let scrollView = UIScrollView()
scrollView.frame = CGRectMake(0, 0, 280, 400) // Height within screen size
scrollView.addSubview(label)
scrollView.contentSize = CGSizeMake(label.bounds.size) // set scrollview content size to label size

Then initialize the popup controller with the scrollview as a custom view following the documentation.

**Closed by carsonperrotti** 2016-07-14 15:48 UTC
Labels: Question / Support
